# Generated by Django 5.0.6 on 2024-05-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
