# Generated by Django 5.0.3 on 2024-03-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
