# Generated by Django 5.0.3 on 2024-03-22 11:19

import user_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics', validators=[user_auth.models.max_file_size]),
        ),
    ]
