# Generated by Django 5.0.4 on 2024-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_allergy',
            name='severity',
            field=models.CharField(blank=True, choices=[('Not Defined', 'Not Defined'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Extreme', 'Extreme')], default='Not Defined', max_length=20),
        ),
        migrations.AddField(
            model_name='patient_medication',
            name='severity',
            field=models.CharField(blank=True, choices=[('Not Defined', 'Not Defined'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Extreme', 'Extreme')], default='Not Defined', max_length=20),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='severity',
            field=models.CharField(blank=True, choices=[('Not Defined', 'Not Defined'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Extreme', 'Extreme')], default='Not Defined', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='alcohol_status',
            field=models.CharField(blank=True, choices=[('Not Defined', 'Not Defined'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Extreme', 'Extreme')], default='Not Defined', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='illegal_items_status',
            field=models.CharField(blank=True, choices=[('Not Defined', 'Not Defined'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Extreme', 'Extreme')], default='Not Defined', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient_medical_history',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('Not Defined', 'Not Defined'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Extreme', 'Extreme')], default='Not Defined', max_length=20),
        ),
    ]
