# Generated by Django 5.0.4 on 2024-04-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_allergy_severity_patient_medication_severity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Allergy',
            new_name='Disease',
        ),
        migrations.RenameModel(
            old_name='Patient_allergy',
            new_name='Patient_disease',
        ),
        migrations.RenameField(
            model_name='patient_disease',
            old_name='allergy',
            new_name='disease',
        ),
        migrations.AlterUniqueTogether(
            name='patient_disease',
            unique_together={('patient', 'disease')},
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('report_date', models.DateField()),
                ('accession_number', models.CharField(max_length=255)),
                ('report_copy', models.FileField(blank=True, upload_to='lab_reports/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=255)),
                ('reference_range', models.TextField(blank=True)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.labreport')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.labtest')),
            ],
        ),
    ]
